//! Auto-generated by `datalink_shim_duckdb_dynlink_emit::emit_dynlink`
//! (Phase A, opaque-blob scalar dispatch). Do NOT edit by hand — regenerate.
#![allow(unused_imports, dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]

use std::sync::atomic::AtomicU32;

mod bindings {
    wit_bindgen::generate!({
        path: "wit",
        world: "bridge",
        generate_all,
    });
}

use bindings::duckdb::extension::types::{
    Capabilitykind, Duckerror, Duckvalue, Funcflags, Invokeinfo, Logicaltype, Resultset,
};
use bindings::duckdb::extension::runtime;
use bindings::duckdb::extension::runtime_ext;
use bindings::duckdb::extension::catalog;
use bindings::exports::duckdb::extension::guest::{self as guest_export, Guest as GuestGuest, Loadresult};
use bindings::exports::duckdb::extension::callback_dispatch::{
    self as cb_export, Guest as CallbackGuest,
};

use bindings::compose::dynlink::linker;

const PROVIDER_ID: &str = "timescale_toolkit-composed";
const EXTENSION_ROOT: &str = "timescale";
const CATALOG_EXTENSION: &str = "timescaledb";
const CATALOG_VERSION: &str = "2.19.0";

fn resolve() -> Result<linker::Instance, Duckerror> {
    linker::resolve_by_id(&PROVIDER_ID.to_string())
        .map_err(|e| Duckerror::Internal(format!("dynlink resolve('{}'): {:?}", PROVIDER_ID, e)))
}

// -----------------------------------------------------------
// CBOR envelope (mirrors provider crate's Request/Response).
// -----------------------------------------------------------

#[derive(Debug, Clone)]
enum CborValue {
    Null,
    Bool(bool),
    Int(i64),
    Uint(u64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
    List(Vec<CborValue>),
}

impl serde::Serialize for CborValue {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        match self {
            CborValue::Null => s.serialize_unit(),
            CborValue::Bool(b) => s.serialize_bool(*b),
            CborValue::Int(i) => s.serialize_i64(*i),
            CborValue::Uint(u) => s.serialize_u64(*u),
            CborValue::Float(f) => s.serialize_f64(*f),
            CborValue::Text(t) => s.serialize_str(t),
            CborValue::Bytes(b) => s.serialize_bytes(b),
            CborValue::List(items) => {
                use serde::ser::SerializeSeq;
                let mut seq = s.serialize_seq(Some(items.len()))?;
                for item in items {
                    seq.serialize_element(item)?;
                }
                seq.end()
            }
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
struct Request {
    #[serde(rename = "v")]
    version: u32,
    args: Vec<CborValue>,
}

#[derive(Debug, Clone, serde::Deserialize)]
struct Response {
    #[serde(default)]
    ok: Option<ResponseValue>,
    #[serde(default)]
    err: Option<String>,
}

#[derive(Debug, Clone)]
enum ResponseValue {
    Null,
    Bool(bool),
    Int(i64),
    Uint(u64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
    List(Vec<ResponseValue>),
}

impl<'de> serde::Deserialize<'de> for ResponseValue {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::{Error, MapAccess, SeqAccess, Visitor};
        struct V;
        impl<'de> Visitor<'de> for V {
            type Value = ResponseValue;
            fn expecting(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
                f.write_str("a CBOR value")
            }
            fn visit_unit<E: Error>(self) -> Result<ResponseValue, E> { Ok(ResponseValue::Null) }
            fn visit_none<E: Error>(self) -> Result<ResponseValue, E> { Ok(ResponseValue::Null) }
            fn visit_bool<E: Error>(self, v: bool) -> Result<ResponseValue, E> { Ok(ResponseValue::Bool(v)) }
            fn visit_i64<E: Error>(self, v: i64) -> Result<ResponseValue, E> { Ok(ResponseValue::Int(v)) }
            fn visit_u64<E: Error>(self, v: u64) -> Result<ResponseValue, E> {
                if v <= i64::MAX as u64 { Ok(ResponseValue::Int(v as i64)) }
                else { Ok(ResponseValue::Uint(v)) }
            }
            fn visit_f64<E: Error>(self, v: f64) -> Result<ResponseValue, E> { Ok(ResponseValue::Float(v)) }
            fn visit_str<E: Error>(self, v: &str) -> Result<ResponseValue, E> { Ok(ResponseValue::Text(v.to_string())) }
            fn visit_string<E: Error>(self, v: String) -> Result<ResponseValue, E> { Ok(ResponseValue::Text(v)) }
            fn visit_bytes<E: Error>(self, v: &[u8]) -> Result<ResponseValue, E> { Ok(ResponseValue::Bytes(v.to_vec())) }
            fn visit_byte_buf<E: Error>(self, v: Vec<u8>) -> Result<ResponseValue, E> { Ok(ResponseValue::Bytes(v)) }
            fn visit_seq<A: SeqAccess<'de>>(self, mut s: A) -> Result<ResponseValue, A::Error> {
                let mut items = Vec::new();
                while let Some(v) = s.next_element::<ResponseValue>()? { items.push(v); }
                Ok(ResponseValue::List(items))
            }
            fn visit_map<A: MapAccess<'de>>(self, mut m: A) -> Result<ResponseValue, A::Error> {
                let k: Option<String> = m.next_key()?;
                let k = k.ok_or_else(|| A::Error::custom("empty map"))?;
                let v = match k.as_str() {
                    "Null" => { let _: serde::de::IgnoredAny = m.next_value()?; ResponseValue::Null }
                    "Bool" => ResponseValue::Bool(m.next_value()?),
                    "Int"  => ResponseValue::Int(m.next_value()?),
                    "Uint" => ResponseValue::Uint(m.next_value()?),
                    "Float" => ResponseValue::Float(m.next_value()?),
                    "Text" => ResponseValue::Text(m.next_value()?),
                    "Bytes" => {
                        let b: serde_bytes::ByteBuf = m.next_value()?;
                        ResponseValue::Bytes(b.into_vec())
                    }
                    "List" => ResponseValue::List(m.next_value()?),
                    other => return Err(A::Error::custom(format!("unknown tag: {}", other))),
                };
                Ok(v)
            }
        }
        d.deserialize_any(V)
    }
}

fn encode_request(args: Vec<CborValue>) -> Result<Vec<u8>, Duckerror> {
    let mut out = Vec::new();
    ciborium::into_writer(&Request { version: 1, args }, &mut out)
        .map_err(|e| Duckerror::Internal(format!("cbor encode: {}", e)))?;
    Ok(out)
}

fn decode_response(bytes: &[u8]) -> Result<Response, Duckerror> {
    ciborium::from_reader(bytes)
        .map_err(|e| Duckerror::Internal(format!("cbor decode: {}", e)))
}

fn call(method: &str, args: Vec<CborValue>) -> Result<ResponseValue, Duckerror> {
    let inst = resolve()?;
    let payload = encode_request(args)?;
    let bytes = inst
        .invoke(&method.to_string(), &payload)
        .map_err(|e| Duckerror::Internal(format!("{}: invoke: {:?}", method, e)))?;
    let resp = decode_response(&bytes)?;
    if let Some(err) = resp.err {
        return Err(Duckerror::Internal(format!("{}: {}", method, err)));
    }
    Ok(resp.ok.unwrap_or(ResponseValue::Null))
}

// -----------------------------------------------------------
// duckvalue / ResponseValue marshalling.
// -----------------------------------------------------------

fn duckv_to_cbor(v: &Duckvalue) -> CborValue {
    // Arm names mirror the WIT-bindgen output for the
    // `duckdb:extension@4.0.0/types/duckvalue` variant. See
    // ~/git/ducklink/wit/duckdb-extension/types.wit:97-120.
    match v {
        Duckvalue::Null => CborValue::Null,
        Duckvalue::Boolean(b) => CborValue::Bool(*b),
        Duckvalue::Int8(i) => CborValue::Int(*i as i64),
        Duckvalue::Int16(i) => CborValue::Int(*i as i64),
        Duckvalue::Int32(i) => CborValue::Int(*i as i64),
        Duckvalue::Int64(i) => CborValue::Int(*i),
        Duckvalue::Uint8(u) => CborValue::Int(*u as i64),
        Duckvalue::Uint16(u) => CborValue::Int(*u as i64),
        Duckvalue::Uint32(u) => CborValue::Int(*u as i64),
        Duckvalue::Uint64(u) => CborValue::Uint(*u),
        Duckvalue::Float32(f) => CborValue::Float(*f as f64),
        Duckvalue::Float64(f) => CborValue::Float(*f),
        Duckvalue::Text(s) => CborValue::Text(s.clone()),
        Duckvalue::Blob(b) => CborValue::Bytes(b.clone()),
        // Date / Time / Timestamp / Timestamptz ferry as int64
        // instants (canonical DuckDB storage).
        Duckvalue::Timestamp(i) => CborValue::Int(*i),
        Duckvalue::Timestamptz(i) => CborValue::Int(*i),
        Duckvalue::Date(i) => CborValue::Int(*i as i64),
        Duckvalue::Time(i) => CborValue::Int(*i),
        // Structured arms (Decimal / Interval / Uuid / Complex)
        // ferry as null at Phase A. The provider owns their
        // encoding when Phase B threads structured logical types.
        Duckvalue::Decimal(_)
        | Duckvalue::Interval(_)
        | Duckvalue::Uuid(_)
        | Duckvalue::Complex(_) => CborValue::Null,
    }
}

fn response_to_duckv(v: ResponseValue) -> Duckvalue {
    match v {
        ResponseValue::Null => Duckvalue::Null,
        ResponseValue::Bool(b) => Duckvalue::Boolean(b),
        ResponseValue::Int(i) => Duckvalue::Int64(i),
        ResponseValue::Uint(u) => Duckvalue::Uint64(u),
        ResponseValue::Float(f) => Duckvalue::Float64(f),
        ResponseValue::Text(t) => Duckvalue::Text(t),
        ResponseValue::Bytes(b) => Duckvalue::Blob(b),
        ResponseValue::List(_) => Duckvalue::Null,
    }
}

// -----------------------------------------------------------
// Columnar hot-path helpers (call_scalar_batch_col).
//
// Simplified vs. the fully-typed postgis-ducklink-bridge
// reference: since dynlink Phase A dispatch is opaque-blob,
// we always lift/lower through Duckvalue::Blob columns. That
// keeps the per-row hot path scalar-Blob-only; multi-shape
// dispatch is a follow-up when the catalog carries logical
// types.
// -----------------------------------------------------------

use bindings::duckdb::extension::column_types;

fn cv_is_valid(validity: &[u8], i: usize) -> bool {
    if validity.is_empty() { return true; }
    let byte = i / 8;
    let bit = i % 8;
    (validity.get(byte).copied().unwrap_or(0) >> bit) & 1 == 1
}

fn colvec_get(cv: &column_types::Colvec, i: usize) -> Duckvalue {
    if !cv_is_valid(cv.validity.as_slice(), i) {
        return Duckvalue::Null;
    }
    match &cv.data {
        column_types::Column::Boolean(xs) => xs.get(i).copied().map(Duckvalue::Boolean).unwrap_or(Duckvalue::Null),
        column_types::Column::Int64(xs) => xs.get(i).copied().map(Duckvalue::Int64).unwrap_or(Duckvalue::Null),
        column_types::Column::Uint64(xs) => xs.get(i).copied().map(Duckvalue::Uint64).unwrap_or(Duckvalue::Null),
        column_types::Column::Float64(xs) => xs.get(i).copied().map(Duckvalue::Float64).unwrap_or(Duckvalue::Null),
        column_types::Column::Int32(xs) => xs.get(i).copied().map(Duckvalue::Int32).unwrap_or(Duckvalue::Null),
        column_types::Column::Int8(xs) => xs.get(i).copied().map(Duckvalue::Int8).unwrap_or(Duckvalue::Null),
        column_types::Column::Int16(xs) => xs.get(i).copied().map(Duckvalue::Int16).unwrap_or(Duckvalue::Null),
        column_types::Column::Uint8(xs) => xs.get(i).copied().map(Duckvalue::Uint8).unwrap_or(Duckvalue::Null),
        column_types::Column::Uint16(xs) => xs.get(i).copied().map(Duckvalue::Uint16).unwrap_or(Duckvalue::Null),
        column_types::Column::Uint32(xs) => xs.get(i).copied().map(Duckvalue::Uint32).unwrap_or(Duckvalue::Null),
        column_types::Column::Float32(xs) => xs.get(i).copied().map(Duckvalue::Float32).unwrap_or(Duckvalue::Null),
        column_types::Column::Timestamp(xs) => xs.get(i).copied().map(Duckvalue::Timestamp).unwrap_or(Duckvalue::Null),
        column_types::Column::Date(xs) => xs.get(i).copied().map(Duckvalue::Date).unwrap_or(Duckvalue::Null),
        column_types::Column::Time(xs) => xs.get(i).copied().map(Duckvalue::Time).unwrap_or(Duckvalue::Null),
        column_types::Column::Timestamptz(xs) => xs.get(i).copied().map(Duckvalue::Timestamptz).unwrap_or(Duckvalue::Null),
        column_types::Column::Text(xs) => xs.get(i).cloned().map(Duckvalue::Text).unwrap_or(Duckvalue::Null),
        column_types::Column::Blob(xs) => xs.get(i).cloned().map(Duckvalue::Blob).unwrap_or(Duckvalue::Null),
        // Decimal / Interval / Uuid / Complex column arms are
        // rendered as Null in the Phase A opaque-blob path.
        _ => Duckvalue::Null,
    }
}

fn validate_colvec_rows(args: &[column_types::Colvec]) -> Result<usize, Duckerror> {
    let n_rows = if args.is_empty() { 0 } else { args[0].rows as usize };
    for (j, cv) in args.iter().enumerate() {
        if cv.rows as usize != n_rows {
            return Err(Duckerror::Internal(format!(
                "columnar dispatch: arg-column {} has rows={} but expected {}",
                j, cv.rows, n_rows
            )));
        }
    }
    Ok(n_rows)
}

fn materialize_row(args: &[column_types::Colvec], i: usize, out: &mut Vec<Duckvalue>) {
    out.clear();
    if out.capacity() < args.len() {
        out.reserve(args.len() - out.capacity());
    }
    for cv in args {
        out.push(colvec_get(cv, i));
    }
}

/// Lower a `Vec<Duckvalue>` (per-row scalar returns) into a
/// typed `Colvec`. Uses a TWO-PASS approach so that NULL rows
/// preceding the first non-NULL row still land in the eventual
/// arm's buffer as zero placeholders (single-pass "pick on first
/// non-NULL" left the pre-arm nulls in `blobs`, giving a
/// buffer.len() < rows off-by-one when the picked arm was not
/// Blob — every subsequent lookup was misaligned).
///
/// Pass 1 walks `&values` to determine the arm (and rejects
/// heterogeneous batches / unsupported Decimal/Interval/Uuid/
/// Complex arms). Pass 2 consumes `values` and pushes real
/// values or zero placeholders into that arm's buffer so the
/// buffer index matches the row index; the validity bitmap
/// carries the actual NULL rows. A colvec of all-NULLs is
/// lowered as Blob (chosen arbitrarily: no data buffer is ever
/// addressed since the validity bitmap zeros every row).
fn values_to_colvec(values: Vec<Duckvalue>) -> Result<column_types::Colvec, Duckerror> {
    let n = values.len();
    let rows = n as u32;
    let mut bits: Vec<u8> = vec![0u8; (n + 7) / 8];
    let mut any_null = false;

    // Discriminator: which arm we picked, populated on first
    // non-NULL row. Repeated per-arm buffers avoid an enum tag
    // in the hot path and let the compiler prove exhaustiveness.
    #[derive(Clone, Copy, PartialEq, Eq, Debug)]
    enum Arm {
        Unknown,
        Boolean,
        Int8, Int16, Int32, Int64,
        Uint8, Uint16, Uint32, Uint64,
        Float32, Float64,
        Text, Blob,
        Date, Time, Timestamp, Timestamptz,
    }

    fn arm_of(v: &Duckvalue) -> Option<Arm> {
        Some(match v {
            Duckvalue::Boolean(_) => Arm::Boolean,
            Duckvalue::Int8(_) => Arm::Int8,
            Duckvalue::Int16(_) => Arm::Int16,
            Duckvalue::Int32(_) => Arm::Int32,
            Duckvalue::Int64(_) => Arm::Int64,
            Duckvalue::Uint8(_) => Arm::Uint8,
            Duckvalue::Uint16(_) => Arm::Uint16,
            Duckvalue::Uint32(_) => Arm::Uint32,
            Duckvalue::Uint64(_) => Arm::Uint64,
            Duckvalue::Float32(_) => Arm::Float32,
            Duckvalue::Float64(_) => Arm::Float64,
            Duckvalue::Text(_) => Arm::Text,
            Duckvalue::Blob(_) => Arm::Blob,
            Duckvalue::Date(_) => Arm::Date,
            Duckvalue::Time(_) => Arm::Time,
            Duckvalue::Timestamp(_) => Arm::Timestamp,
            Duckvalue::Timestamptz(_) => Arm::Timestamptz,
            Duckvalue::Null
            | Duckvalue::Decimal(_)
            | Duckvalue::Interval(_)
            | Duckvalue::Uuid(_)
            | Duckvalue::Complex(_) => return None,
        })
    }

    fn mismatch(expected: &Arm, actual: &Duckvalue) -> Duckerror {
        Duckerror::Internal(format!(
            "values_to_colvec: column arm mismatch (expected={:?}, saw variant with tag {:?}); \
             heterogeneous rows in a single columnar batch are unsupported",
            expected, core::mem::discriminant(actual),
        ))
    }

    // ---- Pass 1: pick the arm across every non-NULL row. ----
    let mut arm = Arm::Unknown;
    for (i, v) in values.iter().enumerate() {
        if matches!(v, Duckvalue::Null) {
            any_null = true;
            continue;
        }
        // Refuse unsupported (Decimal/Interval/Uuid/Complex)
        // returns explicitly — the old code silently NULLed them.
        let this_arm = arm_of(v).ok_or_else(|| Duckerror::Internal(format!(
            "values_to_colvec: unsupported column arm for row {} (Decimal/Interval/Uuid/Complex \
             lowering is not yet implemented in the dynlink emit)",
            i,
        )))?;
        if arm == Arm::Unknown {
            arm = this_arm;
        } else if arm != this_arm {
            return Err(mismatch(&arm, v));
        }
    }

    // ---- Pass 2: allocate the chosen arm's buffer at exact
    // length and materialize (real values for non-NULL rows,
    // zero placeholders for NULL rows).
    let mut booleans: Vec<bool> = Vec::new();
    let mut int8s: Vec<i8> = Vec::new();
    let mut int16s: Vec<i16> = Vec::new();
    let mut int32s: Vec<i32> = Vec::new();
    let mut int64s: Vec<i64> = Vec::new();
    let mut uint8s: Vec<u8> = Vec::new();
    let mut uint16s: Vec<u16> = Vec::new();
    let mut uint32s: Vec<u32> = Vec::new();
    let mut uint64s: Vec<u64> = Vec::new();
    let mut float32s: Vec<f32> = Vec::new();
    let mut float64s: Vec<f64> = Vec::new();
    let mut texts: Vec<String> = Vec::new();
    let mut blobs: Vec<Vec<u8>> = Vec::new();
    let mut dates: Vec<i32> = Vec::new();
    let mut times: Vec<i64> = Vec::new();
    let mut timestamps: Vec<i64> = Vec::new();
    let mut timestamptzs: Vec<i64> = Vec::new();

    for (i, v) in values.into_iter().enumerate() {
        if matches!(v, Duckvalue::Null) {
            // Placeholder so the buffer index tracks the row
            // index; the validity bit stays 0.
            match arm {
                Arm::Unknown | Arm::Blob => blobs.push(Vec::new()),
                Arm::Boolean => booleans.push(false),
                Arm::Int8 => int8s.push(0),
                Arm::Int16 => int16s.push(0),
                Arm::Int32 => int32s.push(0),
                Arm::Int64 => int64s.push(0),
                Arm::Uint8 => uint8s.push(0),
                Arm::Uint16 => uint16s.push(0),
                Arm::Uint32 => uint32s.push(0),
                Arm::Uint64 => uint64s.push(0),
                Arm::Float32 => float32s.push(0.0),
                Arm::Float64 => float64s.push(0.0),
                Arm::Text => texts.push(String::new()),
                Arm::Date => dates.push(0),
                Arm::Time => times.push(0),
                Arm::Timestamp => timestamps.push(0),
                Arm::Timestamptz => timestamptzs.push(0),
            }
            continue;
        }
        bits[i / 8] |= 1u8 << (i % 8);
        match v {
            Duckvalue::Boolean(b) => booleans.push(b),
            Duckvalue::Int8(x) => int8s.push(x),
            Duckvalue::Int16(x) => int16s.push(x),
            Duckvalue::Int32(x) => int32s.push(x),
            Duckvalue::Int64(x) => int64s.push(x),
            Duckvalue::Uint8(x) => uint8s.push(x),
            Duckvalue::Uint16(x) => uint16s.push(x),
            Duckvalue::Uint32(x) => uint32s.push(x),
            Duckvalue::Uint64(x) => uint64s.push(x),
            Duckvalue::Float32(x) => float32s.push(x),
            Duckvalue::Float64(x) => float64s.push(x),
            Duckvalue::Text(s) => texts.push(s),
            Duckvalue::Blob(b) => blobs.push(b),
            Duckvalue::Date(x) => dates.push(x),
            Duckvalue::Time(x) => times.push(x),
            Duckvalue::Timestamp(x) => timestamps.push(x),
            Duckvalue::Timestamptz(x) => timestamptzs.push(x),
            // Null / unsupported: already handled above (or
            // rejected in pass 1).
            _ => unreachable!("arm_of admitted a variant we didn't push"),
        }
    }
    let validity = if any_null { bits } else { Vec::new() };
    let data = match arm {
        Arm::Unknown | Arm::Blob => column_types::Column::Blob(blobs),
        Arm::Boolean => column_types::Column::Boolean(booleans),
        Arm::Int8 => column_types::Column::Int8(int8s),
        Arm::Int16 => column_types::Column::Int16(int16s),
        Arm::Int32 => column_types::Column::Int32(int32s),
        Arm::Int64 => column_types::Column::Int64(int64s),
        Arm::Uint8 => column_types::Column::Uint8(uint8s),
        Arm::Uint16 => column_types::Column::Uint16(uint16s),
        Arm::Uint32 => column_types::Column::Uint32(uint32s),
        Arm::Uint64 => column_types::Column::Uint64(uint64s),
        Arm::Float32 => column_types::Column::Float32(float32s),
        Arm::Float64 => column_types::Column::Float64(float64s),
        Arm::Text => column_types::Column::Text(texts),
        Arm::Date => column_types::Column::Date(dates),
        Arm::Time => column_types::Column::Time(times),
        Arm::Timestamp => column_types::Column::Timestamp(timestamps),
        Arm::Timestamptz => column_types::Column::Timestamptz(timestamptzs),
    };
    Ok(column_types::Colvec { rows, validity, data })
}

fn scalar_name_by_arm_idx(arm: usize) -> Option<&'static str> {
    match arm as u32 {
        0 => Some("average"),
        1 => Some("average_x"),
        2 => Some("average_y"),
        3 => Some("corr"),
        4 => Some("counter_zero_time"),
        5 => Some("covariance"),
        6 => Some("delta"),
        7 => Some("determination_coeff"),
        8 => Some("extrapolated_delta"),
        9 => Some("extrapolated_rate"),
        10 => Some("first_time"),
        11 => Some("first_val"),
        12 => Some("gauge_zero_time"),
        13 => Some("idelta_left"),
        14 => Some("idelta_right"),
        15 => Some("integral"),
        16 => Some("intercept"),
        17 => Some("irate_left"),
        18 => Some("irate_right"),
        19 => Some("kurtosis"),
        20 => Some("kurtosis_x"),
        21 => Some("kurtosis_y"),
        22 => Some("last_time"),
        23 => Some("last_val"),
        24 => Some("num_changes"),
        25 => Some("num_elements"),
        26 => Some("num_resets"),
        27 => Some("rate"),
        28 => Some("skewness"),
        29 => Some("skewness_x"),
        30 => Some("skewness_y"),
        31 => Some("slope"),
        32 => Some("stddev"),
        33 => Some("stddev_x"),
        34 => Some("stddev_y"),
        35 => Some("sum"),
        36 => Some("sum_x"),
        37 => Some("sum_y"),
        38 => Some("time_delta"),
        39 => Some("variance"),
        40 => Some("variance_x"),
        41 => Some("variance_y"),
        42 => Some("with_bounds"),
        43 => Some("x_intercept"),
        _ => None,
    }
}

/// SQL-name aliasing: translate a compact-form SQL name (e.g.
/// `st_geomfromtext`) to its WIT-canonical (long) form
/// (`st_geom_from_text`) before kebab-casing to the provider
/// method name. The catalog carries both spellings as scalars in
/// `leaf.scalars` (both must register with DuckDB so callers can
/// use either), and as first-class `[[aliases]]` entries. The
/// provider dispatch only matches the WIT-canonical form; the
/// bridge's `dispatch_call_scalar` calls `canonical_for(name)` so
/// both spellings route to the same provider arm.
fn canonical_for(name: &str) -> &str {
    match name {
        other => other,
    }
}

// ────────────────────────────────────────────────────────────
// Handle table + register block.
//
// Every scalar the catalog names gets exactly one runtime
// handle (allocated by NEXT_HANDLE.fetch_add at register time)
// and one dense arm_idx (assigned by codegen). `handle_table`
// maps handle → arm_idx; the dispatch arms (call_scalar +
// call_scalar_batch_col) look up the arm and delegate to the
// per-arm provider method through the CBOR envelope.
// ────────────────────────────────────────────────────────────

fn handle_table() -> &'static std::sync::Mutex<std::collections::HashMap<u32, usize>> {
    static T: std::sync::OnceLock<std::sync::Mutex<std::collections::HashMap<u32, usize>>> =
        std::sync::OnceLock::new();
    T.get_or_init(|| std::sync::Mutex::new(std::collections::HashMap::new()))
}

// Phase 9.3.next: aggregate + table dispatch handle tables.
// Kept structurally uniform with the scalar handle_table so a
// future consolidation into a single enum-tagged table is a
// one-liner. Empty when the catalog has no aggregates / tables.
fn aggregate_handle_table() -> &'static std::sync::Mutex<std::collections::HashMap<u32, usize>> {
    static T: std::sync::OnceLock<std::sync::Mutex<std::collections::HashMap<u32, usize>>> =
        std::sync::OnceLock::new();
    T.get_or_init(|| std::sync::Mutex::new(std::collections::HashMap::new()))
}

fn table_handle_table() -> &'static std::sync::Mutex<std::collections::HashMap<u32, usize>> {
    static T: std::sync::OnceLock<std::sync::Mutex<std::collections::HashMap<u32, usize>>> =
        std::sync::OnceLock::new();
    T.get_or_init(|| std::sync::Mutex::new(std::collections::HashMap::new()))
}

fn identity_cast_handles() -> &'static std::sync::Mutex<std::collections::HashSet<u32>> {
    static T: std::sync::OnceLock<std::sync::Mutex<std::collections::HashSet<u32>>> = std::sync::OnceLock::new();
    T.get_or_init(|| std::sync::Mutex::new(std::collections::HashSet::new()))
}

static NEXT_HANDLE: AtomicU32 = AtomicU32::new(1);


fn register_scalars() -> Result<(), Duckerror> {
    // Acquire the base scalar-registry capability from the host.
    // Fix (#834 followup): the previous implementation used
    // `runtime-ext.register-scalar-ex` with an empty arg list
    // (`args: Vec::new()` + `varargs: Some(&Logicaltype::Blob)`)
    // — variadic-Blob for every scalar. That erased the per-fn
    // arity + arg logicaltypes DuckDB needs at bind time (e.g.
    // `st_distance(GEOMETRY, GEOMETRY) -> DOUBLE` bound as
    // `st_distance(BLOB...) -> BLOB`, so callers threading typed
    // arguments couldn't overload-resolve). The base
    // `runtime.scalar-registry.register` path emits the actual
    // arity + per-arg + return logicaltype from the sibling
    // shim-interface DB (see `emit_dynlink::load_scalar_sigs`).
    let capability = runtime::get_capability(Capabilitykind::Scalar)
        .ok_or_else(|| Duckerror::Internal("host did not expose scalar capability".into()))?;
    let registry = match capability {
        runtime::Capability::Scalar(r) => r,
        _ => {
            return Err(Duckerror::Internal(
                "scalar capability returned unexpected variant".into(),
            ));
        }
    };
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 0usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("average (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["average".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "average",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 1usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("average_x (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["average_x".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "average_x",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 2usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("average_y (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["average_y".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "average_y",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 3usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("corr (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["corr".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "corr",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 4usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("counter_zero_time (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["counter_zero_time".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "counter_zero_time",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 5usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("covariance (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["covariance".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "covariance",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 6usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("delta (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["delta".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "delta",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 7usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("determination_coeff (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["determination_coeff".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "determination_coeff",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 8usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("extrapolated_delta (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["extrapolated_delta".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "extrapolated_delta",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 9usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("extrapolated_rate (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["extrapolated_rate".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "extrapolated_rate",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 10usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("first_time (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["first_time".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "first_time",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 11usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("first_val (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["first_val".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "first_val",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 12usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("gauge_zero_time (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["gauge_zero_time".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "gauge_zero_time",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 13usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("idelta_left (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["idelta_left".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "idelta_left",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 14usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("idelta_right (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["idelta_right".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "idelta_right",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 15usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("integral (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["integral".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "integral",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 16usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("intercept (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["intercept".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "intercept",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 17usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("irate_left (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["irate_left".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "irate_left",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 18usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("irate_right (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["irate_right".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "irate_right",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 19usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("kurtosis (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["kurtosis".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "kurtosis",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 20usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("kurtosis_x (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["kurtosis_x".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "kurtosis_x",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 21usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("kurtosis_y (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["kurtosis_y".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "kurtosis_y",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 22usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("last_time (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["last_time".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "last_time",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 23usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("last_val (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["last_val".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "last_val",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 24usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("num_changes (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["num_changes".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "num_changes",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 25usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("num_elements (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["num_elements".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "num_elements",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 26usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("num_resets (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["num_resets".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "num_resets",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 27usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("rate (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["rate".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "rate",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 28usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("skewness (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["skewness".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "skewness",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 29usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("skewness_x (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["skewness_x".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "skewness_x",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 30usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("skewness_y (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["skewness_y".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "skewness_y",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 31usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("slope (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["slope".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "slope",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 32usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("stddev (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["stddev".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "stddev",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 33usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("stddev_x (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["stddev_x".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "stddev_x",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 34usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("stddev_y (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["stddev_y".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "stddev_y",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 35usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("sum (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["sum".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "sum",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 36usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("sum_x (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["sum_x".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "sum_x",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 37usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("sum_y (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["sum_y".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "sum_y",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 38usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("time_delta (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["time_delta".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "time_delta",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 39usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("variance (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["variance".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "variance",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 40usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("variance_x (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["variance_x".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "variance_x",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 41usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Text },
            ];
        let opts = runtime::Funcopts {
            description: Some("variance_y (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["variance_y".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "variance_y",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 42usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("with_bounds (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["with_bounds".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "with_bounds",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        handle_table()
            .lock()
            .expect("scalar handle mutex poisoned")
            .insert(handle, 43usize);
        let callback = runtime::ScalarCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("x_intercept (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["x_intercept".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "x_intercept",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    Ok(())
}

fn register_aggregates() -> Result<(), Duckerror> {
    // Best-effort: hosts that don't expose the aggregate capability
    // still let scalars register (the scalar-only bridges shipped in
    // Phase A). Log-and-continue so the emit stays useful in both
    // shapes.
    let Some(capability) = runtime::get_capability(Capabilitykind::Aggregate) else {
        if true {
            eprintln!("[dynlink-emit] host did not expose aggregate capability; skipping 8 aggregate(s)");
        }
        return Ok(());
    };
    let registry = match capability {
        runtime::Capability::Aggregate(r) => r,
        _ => {
            return Err(Duckerror::Internal(
                "aggregate capability returned unexpected variant".into(),
            ));
        }
    };
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        aggregate_handle_table()
            .lock()
            .expect("aggregate handle mutex poisoned")
            .insert(handle, 0usize);
        let callback = runtime::AggregateCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg2".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("counter_agg (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["counter_agg".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "counter_agg",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        aggregate_handle_table()
            .lock()
            .expect("aggregate handle mutex poisoned")
            .insert(handle, 1usize);
        let callback = runtime::AggregateCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg2".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("gauge_agg (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["gauge_agg".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "gauge_agg",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        aggregate_handle_table()
            .lock()
            .expect("aggregate handle mutex poisoned")
            .insert(handle, 2usize);
        let callback = runtime::AggregateCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("rolling (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["rolling".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "rolling",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        aggregate_handle_table()
            .lock()
            .expect("aggregate handle mutex poisoned")
            .insert(handle, 3usize);
        let callback = runtime::AggregateCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("rollup (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["rollup".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "rollup",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        aggregate_handle_table()
            .lock()
            .expect("aggregate handle mutex poisoned")
            .insert(handle, 4usize);
        let callback = runtime::AggregateCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("stats_agg (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["stats_agg".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "stats_agg",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        aggregate_handle_table()
            .lock()
            .expect("aggregate handle mutex poisoned")
            .insert(handle, 5usize);
        let callback = runtime::AggregateCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("stats_agg_no_inv (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["stats_agg_no_inv".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "stats_agg_no_inv",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        aggregate_handle_table()
            .lock()
            .expect("aggregate handle mutex poisoned")
            .insert(handle, 6usize);
        let callback = runtime::AggregateCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("stats_agg_tf (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["stats_agg_tf".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "stats_agg_tf",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    {
        let handle = NEXT_HANDLE.fetch_add(1, core::sync::atomic::Ordering::Relaxed);
        aggregate_handle_table()
            .lock()
            .expect("aggregate handle mutex poisoned")
            .insert(handle, 7usize);
        let callback = runtime::AggregateCallback::new(handle);
        let args: Vec<runtime::Funcarg> = vec![
                runtime::Funcarg { name: Some("arg0".into()), logical: Logicaltype::Text },
                runtime::Funcarg { name: Some("arg1".into()), logical: Logicaltype::Blob },
                runtime::Funcarg { name: Some("arg2".into()), logical: Logicaltype::Blob },
            ];
        let opts = runtime::Funcopts {
            description: Some("time_weight (sqlink-shim-codegen --dynlink)".into()),
            tags: vec!["time_weight".into()],
            attributes: Funcflags::DETERMINISTIC | Funcflags::STATELESS,
        };
        registry.register(
            "time_weight",
            &args,
            &Logicaltype::Blob,
            callback,
            Some(&opts),
        )?;
    }
    Ok(())
}

fn register_tables() -> Result<(), Duckerror> {
    let Some(capability) = runtime::get_capability(Capabilitykind::Table) else {
        if false {
            eprintln!("[dynlink-emit] host did not expose table capability; skipping 0 table-function(s)");
        }
        return Ok(());
    };
    let registry = match capability {
        runtime::Capability::Table(r) => r,
        _ => {
            return Err(Duckerror::Internal(
                "table capability returned unexpected variant".into(),
            ));
        }
    };
    Ok(())
}

// -----------------------------------------------------------
// Guest impls.
// -----------------------------------------------------------

struct Component;

impl GuestGuest for Component {
    fn load() -> Result<Loadresult, Duckerror> {
        register_scalars()?;
        register_aggregates()?;
        register_tables()?;
        Ok(Loadresult {
            name: EXTENSION_ROOT.to_string(),
            version: Some(CATALOG_VERSION.to_string()),
            requires: vec![Capabilitykind::Scalar],
        })
    }
    fn reconfigure(_keys: Vec<String>) -> Result<bool, Duckerror> { Ok(false) }
    fn shutdown() -> Result<bool, Duckerror> { Ok(false) }
}

fn dispatch_call_scalar(
    handle: u32,
    args: Vec<Duckvalue>,
) -> Result<Duckvalue, Duckerror> {
    let arm_idx = handle_table()
        .lock()
        .expect("scalar handle mutex poisoned")
        .get(&handle)
        .copied()
        .ok_or_else(|| Duckerror::Internal(format!("unknown scalar handle {}", handle)))?;
    let name = scalar_name_by_arm_idx(arm_idx)
        .ok_or_else(|| Duckerror::Internal(format!("unknown scalar arm {}", arm_idx)))?;
    // Null-propagation: any NULL argument short-circuits to NULL.
    if args.iter().any(|v| matches!(v, Duckvalue::Null)) {
        return Ok(Duckvalue::Null);
    }
    // Alias translation: SQL name → WIT-canonical → provider method
    // (kebab-case). Compact-form SQL names (e.g. `st_geomfromtext`)
    // route through `canonical_for` to their long form
    // (`st_geom_from_text`) before kebab-casing; non-alias names
    // pass through unchanged. See `canonical_for` above.
    let canonical = canonical_for(name);
    let method = canonical.replace('_', "-");
    let cbor_args: Vec<CborValue> = args.iter().map(duckv_to_cbor).collect();
    let resp = call(&method, cbor_args)?;
    Ok(response_to_duckv(resp))
}

fn aggregate_name_by_arm_idx(arm: usize) -> Option<&'static str> {
    match arm as u32 {
        0 => Some("counter_agg"),
        1 => Some("gauge_agg"),
        2 => Some("rolling"),
        3 => Some("rollup"),
        4 => Some("stats_agg"),
        5 => Some("stats_agg_no_inv"),
        6 => Some("stats_agg_tf"),
        7 => Some("time_weight"),
        _ => None,
    }
}

fn table_name_by_arm_idx(arm: usize) -> Option<&'static str> {
    match arm as u32 {
        _ => None,
    }
}

/// Aggregate dispatch (Phase 9.3.next). Whole-group call: the host
/// hands us every row's arg columns; we lift each row to a CBOR list
/// and ship the accumulated list-of-lists to the provider under the
/// aggregate's canonical name. The provider owns the semantic
/// fold (average, extent, cluster, …); the bridge is a CBOR tunnel.
fn dispatch_call_aggregate(
    handle: u32,
    args: Vec<bindings::duckdb::extension::column_types::Colvec>,
) -> Result<Duckvalue, Duckerror> {
    let arm_idx = aggregate_handle_table()
        .lock()
        .expect("aggregate handle mutex poisoned")
        .get(&handle)
        .copied()
        .ok_or_else(|| Duckerror::Internal(format!("unknown aggregate handle {}", handle)))?;
    let name = aggregate_name_by_arm_idx(arm_idx)
        .ok_or_else(|| Duckerror::Internal(format!("unknown aggregate arm {}", arm_idx)))?;
    let n_rows = validate_colvec_rows(&args)?;
    let n_args = args.len();
    // Columnar wire shape for aggregate dispatch: each column becomes a
    // separate positional arg to the provider, containing a FLAT list
    // of that column's per-row CBOR values. For a single-arg aggregate
    // like `st_extent(geom)`, the provider sees `args=[List<Bytes>]` —
    // arg[0] is the flat geometry list, arg[0][0] is a Bytes geometry
    // (matches the shim's expected shape per the arg-shape checker's
    // error message on prior versions of this dispatch).
    //
    // Previous wire (broken) was `args=[List<List<CborValue>>]` — one
    // arg containing a list of per-row lists. The shim's arg-type
    // checker on `st-extent` etc. read `arg[0][0]` as List (a row) and
    // failed shape mismatch (expected Bytes for the geometry).
    //
    // SQL-aggregate NULL-row semantics: skip rows where ANY arg is
    // NULL (matches sum() / avg() defaults) — do the skip BEFORE
    // transposing to columns so all columns see the same row subset.
    let mut cols: Vec<Vec<CborValue>> = (0..n_args)
        .map(|_| Vec::with_capacity(n_rows))
        .collect();
    let mut row_buf: Vec<Duckvalue> = Vec::with_capacity(n_args);
    for i in 0..n_rows {
        materialize_row(&args, i, &mut row_buf);
        if row_buf.iter().any(|v| matches!(v, Duckvalue::Null)) {
            continue;
        }
        for (col_idx, v) in row_buf.iter().enumerate() {
            cols[col_idx].push(duckv_to_cbor(v));
        }
    }
    // Empty non-null row set → aggregate is NULL (matches SQL
    // `SELECT SUM(x) FROM t WHERE 1=0` = NULL). Skip the provider
    // call so the shim doesn't need to special-case empty inputs.
    if cols.first().map_or(true, |c| c.is_empty()) {
        return Ok(Duckvalue::Null);
    }
    let canonical = canonical_for(name);
    let method = canonical.replace('_', "-");
    let cbor_args: Vec<CborValue> = cols.into_iter().map(CborValue::List).collect();
    let resp = call(&method, cbor_args)?;
    Ok(response_to_duckv(resp))
}

/// Table-function dispatch (Phase 9.3.next). Single-shot call: the
/// host hands us the argv values; we ship them through the CBOR
/// envelope and expect a List-of-Bytes (one BLOB per row) response.
/// Any other shape is best-effort wrapped as a single Blob row so
/// the provider stays free to evolve its wire without breaking the
/// bridge.
fn dispatch_call_table(
    handle: u32,
    args: Vec<Duckvalue>,
) -> Result<Resultset, Duckerror> {
    let arm_idx = table_handle_table()
        .lock()
        .expect("table handle mutex poisoned")
        .get(&handle)
        .copied()
        .ok_or_else(|| Duckerror::Internal(format!("unknown table handle {}", handle)))?;
    let name = table_name_by_arm_idx(arm_idx)
        .ok_or_else(|| Duckerror::Internal(format!("unknown table arm {}", arm_idx)))?;
    let canonical = canonical_for(name);
    let method = canonical.replace('_', "-");
    let cbor_args: Vec<CborValue> = args.iter().map(duckv_to_cbor).collect();
    let resp = call(&method, cbor_args)?;
    let rows: Vec<Vec<Duckvalue>> = match resp {
        ResponseValue::List(items) => items
            .into_iter()
            .map(|item| match item {
                ResponseValue::Bytes(b) => vec![Duckvalue::Blob(b)],
                ResponseValue::List(cols) => cols.into_iter().map(response_to_duckv).collect(),
                other => vec![response_to_duckv(other)],
            })
            .collect(),
        ResponseValue::Null => Vec::new(),
        other => vec![vec![response_to_duckv(other)]],
    };
    Ok(rows)
}

impl CallbackGuest for Component {
    fn call_scalar(
        handle: u32,
        args: Vec<Duckvalue>,
        _ctx: Invokeinfo,
    ) -> Result<Duckvalue, Duckerror> {
        dispatch_call_scalar(handle, args)
    }

    fn call_scalar_batch_col(
        handle: u32,
        args: Vec<bindings::duckdb::extension::column_types::Colvec>,
        ctx: Invokeinfo,
    ) -> Result<bindings::duckdb::extension::column_types::Colvec, Duckerror> {
        // Columnar HOT path: convert per-row, delegate to the cold
        // row-major dispatch, then rebuild a colvec. Mirrors the
        // postgis-ducklink-bridge (~/git/postgis-ducklink-bridge/
        // src/lib.rs:2231-2261) reference discipline.
        let n_rows = validate_colvec_rows(&args)?;
        let n_args = args.len();
        let base = ctx.rowindex.unwrap_or(0);
        let mut out: Vec<Duckvalue> = Vec::with_capacity(n_rows);
        let mut row_buf: Vec<Duckvalue> = Vec::with_capacity(n_args);
        for i in 0..n_rows {
            materialize_row(&args, i, &mut row_buf);
            let _row_ctx = Invokeinfo {
                rowindex: Some(base + i as u64),
                iswindow: ctx.iswindow,
            };
            let row_args = core::mem::take(&mut row_buf);
            out.push(dispatch_call_scalar(handle, row_args)?);
        }
        values_to_colvec(out)
    }

    fn call_aggregate_col(
        handle: u32,
        args: Vec<bindings::duckdb::extension::column_types::Colvec>,
    ) -> Result<Duckvalue, Duckerror> {
        dispatch_call_aggregate(handle, args)
    }

    fn call_cast_col(
        handle: u32,
        arg: bindings::duckdb::extension::column_types::Colvec,
    ) -> Result<bindings::duckdb::extension::column_types::Colvec, Duckerror> {
        // Identity casts (GEOMETRY↔BLOB / BOX2D↔BLOB / ...) are
        // physical-representation-preserving: the source and target
        // are both physically BLOB, only the logical tag differs.
        // Return the input column unchanged.
        if identity_cast_handles()
            .lock()
            .expect("identity cast handles mutex poisoned")
            .contains(&handle)
        {
            return Ok(arg);
        }
        Err(Duckerror::Internal("call_cast_col: handle not identity (Phase A)".to_string()))
    }

    fn call_table(handle: u32, args: Vec<Duckvalue>) -> Result<Resultset, Duckerror> {
        dispatch_call_table(handle, args)
    }

    fn call_pragma(_handle: u32, _args: Vec<Duckvalue>) -> Result<Option<Duckvalue>, Duckerror> {
        Err(Duckerror::Internal("call_pragma: unsupported (Phase A)".to_string()))
    }

    fn call_cast(handle: u32, value: Duckvalue) -> Result<Duckvalue, Duckerror> {
        let _ = (handle, value);
        Err(Duckerror::Internal("call_cast: unsupported (Phase A)".to_string()))
    }
}

bindings::export!(Component with_types_in bindings);
